### PR TITLE
Set devservices postgres version to 15

### PR DESCRIPTION
**Pull request by janinko**

### CODE REVIEW

**Comment by janinko** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Comment by thescouser89** [comment]
@janinko Could you update the image to: 'public.ecr.aws/docker/library/postgres:15-bullseye' please? it's a public docker registry mirror with no pull limit from amazon. thanks!

**Comment by janinko** [comment]
retest this please

**Comment by janinko** [comment]
retest this please

**Pull request merged**
